"""
This file is autogenerated to lazily import symbols from '__init__.py'.

Do NOT edit manually.
"""

import importlib

_lazy_imports = {
    "Logger": ("nimbro_utils.node_extensions.logger", "Logger"),
    "ParameterHandler": ("nimbro_utils.node_extensions.parameter_handler", "ParameterHandler"),
    "SensorInterface": ("nimbro_utils.node_extensions.sensor_interface", "SensorInterface"),
    "DepthConverter": ("nimbro_utils.node_extensions.depth_converter", "DepthConverter"),
    "TfOracle": ("nimbro_utils.node_extensions.tf_oracle", "TfOracle"),
    "SelfShutdown": ("nimbro_utils.utility.node", "SelfShutdown"),
    "start_and_spin_node": ("nimbro_utils.utility.node", "start_and_spin_node"),
    "stop_node": ("nimbro_utils.utility.node", "stop_node"),
    "block_until_future_complete": ("nimbro_utils.utility.node", "block_until_future_complete"),
    "create_throttled_subscription": ("nimbro_utils.utility.node", "create_throttled_subscription"),
    "wait_for_message": ("nimbro_utils.utility.node", "wait_for_message"),
    "quaternion_to_rotation_matrix": ("nimbro_utils.utility.geometry", "quaternion_to_rotation_matrix"),
    "quaternion_to_yaw_pitch_roll": ("nimbro_utils.utility.geometry", "quaternion_to_yaw_pitch_roll"),
    "yaw_pitch_roll_to_rotation_matrix": ("nimbro_utils.utility.geometry", "yaw_pitch_roll_to_rotation_matrix"),
    "yaw_pitch_roll_to_quaternion": ("nimbro_utils.utility.geometry", "yaw_pitch_roll_to_quaternion"),
    "rotation_matrix_to_quaternion": ("nimbro_utils.utility.geometry", "rotation_matrix_to_quaternion"),
    "create_point": ("nimbro_utils.utility.geometry", "create_point"),
    "create_vector": ("nimbro_utils.utility.geometry", "create_vector"),
    "create_quaternion": ("nimbro_utils.utility.geometry", "create_quaternion"),
    "create_pose": ("nimbro_utils.utility.geometry", "create_pose"),
    "create_transform": ("nimbro_utils.utility.geometry", "create_transform"),
    "create_pointcloud": ("nimbro_utils.utility.geometry", "create_pointcloud"),
    "convert_transform": ("nimbro_utils.utility.geometry", "convert_transform"),
    "convert_point_and_vector": ("nimbro_utils.utility.geometry", "convert_point_and_vector"),
    "convert_pose_and_transform": ("nimbro_utils.utility.geometry", "convert_pose_and_transform"),
    "laserscan_to_pointcloud": ("nimbro_utils.utility.geometry", "laserscan_to_pointcloud"),
    "message_to_numpy": ("nimbro_utils.utility.geometry", "message_to_numpy"),
    "do_transform": ("nimbro_utils.utility.geometry", "do_transform"),
    "rotate_pose": ("nimbro_utils.utility.geometry", "rotate_pose"),
    "rotation_from_vectors": ("nimbro_utils.utility.geometry", "rotation_from_vectors"),
    "cosine_similarity": ("nimbro_utils.utility.geometry", "cosine_similarity"),
    "quaternion_distance": ("nimbro_utils.utility.geometry", "quaternion_distance"),
    "get_circle_pixels": ("nimbro_utils.utility.geometry", "get_circle_pixels"),
    "get_iou": ("nimbro_utils.utility.geometry", "get_iou"),
    "convert_boxes": ("nimbro_utils.utility.geometry", "convert_boxes"),
    "show_image": ("nimbro_utils.utility.image", "show_image"),
    "save_image": ("nimbro_utils.utility.image", "save_image"),
    "convert_image": ("nimbro_utils.utility.image", "convert_image"),
    "download_image": ("nimbro_utils.utility.image", "download_image"),
    "resize_image": ("nimbro_utils.utility.image", "resize_image"),
    "image_info": ("nimbro_utils.utility.image", "image_info"),
    "visualize_depth": ("nimbro_utils.utility.image", "visualize_depth"),
    "visualize_detections": ("nimbro_utils.utility.image", "visualize_detections"),
    "draw_rectangle": ("nimbro_utils.utility.image", "draw_rectangle"),
    "draw_text": ("nimbro_utils.utility.image", "draw_text"),
    "encode_mask": ("nimbro_utils.utility.image", "encode_mask"),
    "decode_mask": ("nimbro_utils.utility.image", "decode_mask"),
    "erode_or_dilate_mask": ("nimbro_utils.utility.image", "erode_or_dilate_mask"),
    "Color": ("nimbro_utils.utility.color", "Color"),
    "ColorPalette": ("nimbro_utils.utility.color", "ColorPalette"),
    "show_colors": ("nimbro_utils.utility.color", "show_colors"),
    "nimbro": ("nimbro_utils.utility.color", "nimbro"),
    "kelly": ("nimbro_utils.utility.color", "kelly"),
    "monokai": ("nimbro_utils.utility.color", "monokai"),
    "solarized": ("nimbro_utils.utility.color", "solarized"),
    "bonn": ("nimbro_utils.utility.color", "bonn"),
    "night": ("nimbro_utils.utility.color", "night"),
    "wave": ("nimbro_utils.utility.color", "wave"),
    "scream": ("nimbro_utils.utility.color", "scream"),
    "tangerine": ("nimbro_utils.utility.color", "tangerine"),
    "globe": ("nimbro_utils.utility.color", "globe"),
    "x11": ("nimbro_utils.utility.color", "x11"),
    "normalize_string": ("nimbro_utils.utility.string", "normalize_string"),
    "remove_unicode": ("nimbro_utils.utility.string", "remove_unicode"),
    "remove_whitespace": ("nimbro_utils.utility.string", "remove_whitespace"),
    "remove_non_alpha_numeric": ("nimbro_utils.utility.string", "remove_non_alpha_numeric"),
    "remove_emoji": ("nimbro_utils.utility.string", "remove_emoji"),
    "remove_ansi_escape": ("nimbro_utils.utility.string", "remove_ansi_escape"),
    "levenshtein": ("nimbro_utils.utility.string", "levenshtein"),
    "levenshtein_match": ("nimbro_utils.utility.string", "levenshtein_match"),
    "is_url": ("nimbro_utils.utility.string", "is_url"),
    "is_base64": ("nimbro_utils.utility.string", "is_base64"),
    "is_attribute_name": ("nimbro_utils.utility.string", "is_attribute_name"),
    "count_tokens": ("nimbro_utils.utility.string", "count_tokens"),
    "split_sentences": ("nimbro_utils.utility.string", "split_sentences"),
    "extract_json": ("nimbro_utils.utility.string", "extract_json"),
    "escape": ("nimbro_utils.utility.misc", "escape"),
    "assert_type_value": ("nimbro_utils.utility.misc", "assert_type_value"),
    "assert_attribute": ("nimbro_utils.utility.misc", "assert_attribute"),
    "assert_keys": ("nimbro_utils.utility.misc", "assert_keys"),
    "assert_log": ("nimbro_utils.utility.misc", "assert_log"),
    "read_json": ("nimbro_utils.utility.misc", "read_json"),
    "write_json": ("nimbro_utils.utility.misc", "write_json"),
    "read_as_b64": ("nimbro_utils.utility.misc", "read_as_b64"),
    "encode_b64": ("nimbro_utils.utility.misc", "encode_b64"),
    "decode_b64": ("nimbro_utils.utility.misc", "decode_b64"),
    "update_dict": ("nimbro_utils.utility.misc", "update_dict"),
    "count_duplicates": ("nimbro_utils.utility.misc", "count_duplicates"),
    "start_jobs": ("nimbro_utils.utility.misc", "start_jobs"),
    "try_callback": ("nimbro_utils.utility.misc", "try_callback"),
    "convert_stamp": ("nimbro_utils.utility.misc", "convert_stamp"),
    "log_lines": ("nimbro_utils.utility.misc", "log_lines"),
    "in_jupyter_notebook": ("nimbro_utils.utility.misc", "in_jupyter_notebook"),
    "get_package_path": ("nimbro_utils.utility.misc", "get_package_path"),
}

_import_cache = {}

def __getattr__(name):
    if name in _import_cache:
        return _import_cache[name]
    if name in _lazy_imports:
        module_name, attr_name = _lazy_imports[name]
        module = importlib.import_module(module_name)
        attr = getattr(module, attr_name)
        _import_cache[name] = attr
        return attr
    raise AttributeError(f"Module '{__name__}' has no attribute '{name}'.")

def __dir__():
    return sorted(list(globals().keys()) + list(_lazy_imports.keys()))
